root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ."
  bin = "./tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test\\.go$"]
  exclude_unchanged = false
  follow_symlink = false
  log = "build-errors.log"
  kill_delay = "0s"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true

[color]
  app = "green"
  build = "yellow"
  main = "magenta"
  runner = "cyan"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
